name: Lint Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Debug SHAs
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"

      - name: Run commitlint
        run: |
          if git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep .; then
            npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.sha }}
          else
            echo "No new commits to lint"
          fi
