name: Lint Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Debug SHAs and Git Info
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"
          echo "Git Status:"
          git status
          echo "Available Branches:"
          git branch -a
          echo "Recent Commits:"
          git log --oneline -n 5

      - name: Run commitlint
        run: |
          if git merge-base --is-ancestor ${{ github.event.pull_request.base.sha }} ${{ github.sha }}; then
            if git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep .; then
              npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.sha }}
            else
              echo "No new commits to lint"
            fi
          else
            echo "Invalid commit range. Base commit is not an ancestor of head commit."
            echo "Falling back to linting the last commit..."
            npx commitlint --from HEAD~1 --to HEAD
          fi
